apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app-check
            image: busybox
            command:
            - /bin/sh
            - -c
            - echo "Your app is up"
          restartPolicy: OnFailure
