apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprobe
  namespace: demo
spec:
  containers:
    - name: app
      image: gcr.io/k8s-k3s-419811/demo:v1.0.0
      ports:
        - name: http
          containerPort: 8080
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        periodSeconds: 10
        initialDelaySeconds: 15
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ready
          port: 8000
        periodSeconds: 5
        initialDelaySeconds: 20
        failureThreshold: 5
