apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprobe
  namespace: demo
spec:
  containers:
    - name: app
      image: gcr.io/k8s-k3s-419811/demo:v1.0.0
      ports:
        - name: http
          containerPort: 8080
      livenessProbe:
        httpGet:
          path: /
          port: 8000
          scheme: HTTP
        initialDelaySeconds: 15
        periodSeconds: 30